import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BuyElectricity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className={styles.span}>Buy</span>
          Electricity
        </h1>
        <p>Buy electricity at your convenience</p>
      </main>
      <form className={styles.form}>
        <label>Enter your mobile number to login</label>
        <input placeholder="Phone" type="number" />
        <Link href="/welcome">
          <a className={styles.button}>Continue to buy electricity</a>
        </Link>
      </form>
    </div>
  );
}
